name: Build and Push Image to GCP (Google Cloud Platform)

on:
  push:
    branches: [main]
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: pipedrive-challenge
      PROJECT_ID: jaristil-pipedrive-challenge
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true
    
    - name: Build the docker Image
      run: |-
        docker build -t $IMAGE_NAME:$GITHUB_SHA .
    
    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker europe-north1-docker.pkg.dev --quiet

    - name: Push the Docker Image to GCR (Google Container Registry)
      run: |-
        docker tag $IMAGE_NAME:$GITHUB_SHA gcr.io/$PROJECT_ID/$IMAGE_NAME:$GITHUB_SHA
        docker tag $IMAGE_NAME:$GITHUB_SHA gcr.io/$PROJECT_ID/$IMAGE_NAME:$GITHUB_SHA
        docker push  gcr.io/$PROJECT_ID/$IMAGE_NAME:$GITHUB_SHA
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GITHUB_SHA

    - name: Push the Docker Image to Artifact Registry
      run: |-
        docker tag $IMAGE_NAME:$GITHUB_SHA europe-north1-docker.pkg.dev/$PROJECT_ID/$IMAGE_NAME:$GITHUB_SHA
        docker tag $IMAGE_NAME:$GITHUB_SHA europe-north1-docker.pkg.dev/$PROJECT_ID/$IMAGE_NAME:$GITHUB_SHA
        docker push  europe-north1-docker.pkg.dev/$PROJECT_ID/$IMAGE_NAME:$GITHUB_SHA
        docker push europe-north1-docker.pkg.dev/$PROJECT_ID/$IMAGE_NAME:$GITHUB_SHA